## ECE 2112: Advanced Computer Programming and Algorithms

# EXPERIMENT 2: NUMERICAL PYTHON (NUMPY)

**Name:** Rapis, Reese Cassandra T. <br> **Section:** 2ECE-C <br> **Date Submitted:** September 3, 2026

In [2]:
import numpy as np

## A. REPRODUCIBLE NORMALIZATION PROBLEM

Create a reproducible 5x5 random integer array using `ndarray`, then normalize it using the z-score formula so that the resulting array has a mean of 0 and a standard deviation of 1.

In [17]:
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5)) 

# Compute the mean and standard deviation of all 25 elements
X_mean = np.mean(X)
X_std = np.std(X)

# Use the z-score formula to normalize the array
X_normalized = (X - X_mean) / X_std

# Display the original array
print("X:\n", X)

# Display the normalized array
print("\nX_normalized:\n", X_normalized)

# Display the mean and standard deviation of the normalized array as a check
# These should be approximately 0 and 1, respectively
print("\nMean of X_normalized:", X_normalized.mean())
print("\nStd of X_normalized:", X_normalized.std())

X:
 [[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]

X_normalized:
 [[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]

Mean of X_normalized: 0.0

Std of X_normalized: 0.9999999999999999


In [18]:
np.save("X_normalized.npy", X_normalized)

## B. CUBES DIVISIBLE BY 4 PROBLEM

Build a 10x10 array of the cubes of the first 100 positive integers, then use Boolean indexing to select only the cubes that are divisible by 4.

In [10]:
# Create the first 100 positive integers, then cube it
C = np.arange(1, 101) ** 3

# Reshape the 1D array of 100 cubes into a 10x10 array
C = C.reshape(10, 10)

# True wherever an element is divisible by 4
div_by_4 = C[C % 4 == 0]

# Display the shape of C 
print("Shape of C:", C.shape)

# Display the selected values
print("\nArray divided by 4:\n", div_by_4)

# Display the number of selected elements
print("\nNumber of selected elements:", div_by_4.size)

Shape of C: (10, 10)

Array divided by 4:
 [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]

Number of selected elements: 50


In [11]:
np.save("div_by_4.npy", div_by_4)

## C. ABOVE-MEAN SQUARES PROBLEM

Build a 6x6 array of the squares of the first 36 positive integers, compute the mean of the array (`S_mean`), then use Boolean indexing to select only the elements greater than that mean (`above_mean`).

In [21]:
# Create the first 36 positive integers, then square every element
S = np.arange(1, 37) ** 2

# Reshape the 1D array of 36 squares into a 6x6 array in row-major order
S = S.reshape(6, 6)

# Compute the mean of all elements of S
S_mean = S.mean()

# True wherever an element is greater than S_mean
above_mean = S[S > S_mean]

# Display the original array
print("S:\n", X)

# Display the mean 
print("\nS_mean:", S_mean)

# Display the above mean
print("\nAbove Mean:\n", above_mean)

# Display the number of selected elements
print("\nNumber of selected elements:", above_mean.size)

S:
 [[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]

S_mean: 450.1666666666667

Above Mean:
 [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]

Number of selected elements: 15


In [22]:
np.save("above_mean.npy", above_mean)